from .info import (
    MUSIC_RENAMER_AUTHOR,
    MUSIC_RENAMER_AUTHOR_EMAIL,
    MUSIC_RENAMER_DESCRIPTION,
    MUSIC_RENAMER_KEYWORDS,
    MUSIC_RENAMER_LICENSE,
    MUSIC_RENAMER_MAINTAINER,
    MUSIC_RENAMER_MAINTAINER_EMAIL,
    MUSIC_RENAMER_NAME,
    MUSIC_RENAMER_URL,
    MUSIC_RENAMER_VERSION,
    PARSER_DESCRIPTION,
)
from .settings import AUDIO_EXTENSIONS

__all__ = [
    "AUDIO_EXTENSIONS",
    "MUSIC_RENAMER_AUTHOR",
    "MUSIC_RENAMER_AUTHOR_EMAIL",
    "MUSIC_RENAMER_DESCRIPTION",
    "MUSIC_RENAMER_KEYWORDS",
    "MUSIC_RENAMER_LICENSE",
    "MUSIC_RENAMER_MAINTAINER",
    "MUSIC_RENAMER_MAINTAINER_EMAIL",
    "MUSIC_RENAMER_NAME",
    "MUSIC_RENAMER_URL",
    "MUSIC_RENAMER_VERSION",
    "PARSER_DESCRIPTION",
]
