"""
Module with info constants.
"""

PARSER_DESCRIPTION = "Renames audio files based on their metadata and embeds synchronized lyrics."
MUSIC_RENAMER_VERSION = "1.1.0"
MUSIC_RENAMER_NAME = "musren"
MUSIC_RENAMER_DESCRIPTION = "Music file renamer with metadata, lyrics, covers and recognition"
MUSIC_RENAMER_AUTHOR = "cosLatte"
MUSIC_RENAMER_AUTHOR_EMAIL = "gabrielpazruiz02@gmail.com"
MUSIC_RENAMER_MAINTAINER = "Sataros221"
MUSIC_RENAMER_MAINTAINER_EMAIL = "sataros221@gmail.com"
MUSIC_RENAMER_URL = "https://github.com/coslatte/MusRen"
MUSIC_RENAMER_KEYWORDS = "music audio metadata lyrics cover renamer acoustid"
MUSIC_RENAMER_LICENSE = "MIT"